apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
  namespace: metallb-system
  labels:
    app: app-lb
spec:
  selector:
    name: app-lb
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  #loadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443